# Generated by Django 3.2 on 2021-07-28 20:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField()),
                ('api_url', models.URLField(null=True)),
                ('stratum_urls', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PoolStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='mining.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(unique=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('network_hashrate', jsonfield.fields.JSONField(default=dict)),
                ('network_diff', jsonfield.fields.JSONField(default=dict)),
                ('algorithm', models.CharField(blank=True, max_length=6, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='mining.pool')),
            ],
            options={
                'ordering': ['-height'],
            },
        ),
    ]
