# Generated by Django 3.2 on 2021-07-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='data',
        ),
    ]
