# Generated by Django 3.2 on 2021-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_remove_block_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='algorithm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
