# Generated by Django 3.2 on 2021-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_alter_block_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='algorithm',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
