# Generated by Django 3.0.14 on 2021-05-24 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('proforma', jsonfield.fields.JSONField(default=dict)),
                ('status', models.CharField(default='Created', max_length=20)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='Saved', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swapic.Transaction')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SwapicTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swapic.Transaction')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
