# Generated by Django 3.2 on 2021-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_currency_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
