# Generated by Django 3.0 on 2021-03-16 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('proof', models.CharField(default='none', max_length=256)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('previous_hash', models.CharField(blank=True, default='none', max_length=256)),
                ('extra_data', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='TEST', max_length=256)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('block_size', models.IntegerField(default=300)),
                ('total_supply', models.IntegerField(default=100000)),
                ('extra_data', jsonfield.fields.JSONField(default={})),
                ('node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(default=1111)),
                ('name', models.CharField(default='Default', max_length=70)),
                ('locked', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('balance', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32)),
                ('address', models.CharField(default='none', max_length=128)),
                ('public_key', models.CharField(default='none', max_length=1024)),
                ('private_key', models.CharField(default='none', editable=False, max_length=2048)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('telegram_user', models.CharField(blank=True, max_length=70, null=True)),
                ('extra_data', jsonfield.fields.JSONField(default={})),
                ('blockchain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_blockchain', to='ecb.Blockchain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('genesis', 'genesis'), ('pending', 'pending'), ('mempool', 'mempool'), ('canceled', 'canceled'), ('completed', 'completed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('signature', models.CharField(default='none', max_length=256)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, default={})),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='ecb.Block')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='ecb.Wallet')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ecb.Wallet')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='blockchain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_blockchain', to='ecb.Blockchain'),
        ),
    ]
