# Generated by Django 3.0 on 2021-03-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pending',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32),
        ),
    ]
